services:
  tb-playwright-manual:
    entrypoint: ["node", "cli.js", "--headless", "--browser", "chromium", "--no-sandbox", "--port", "4723"]
    container_name: tb-playwright-manual
    restart: unless-stopped
    image: mcr.microsoft.com/playwright/mcp
    ports:
      - 4723:4723