# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: TestBucket

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      DOTNET_INSTALL_DIR: "./.dotnet"

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.102
    - name: Restore dependencies
      run: dotnet restore src/TestBucket.sln
    - name: Build
      run: dotnet build --no-restore src/TestBucket.sln
   
    - name: Test
      shell: pwsh
      run: ./run_tests.ps1
      with:
        name: tests
        path: **/xunit.xml
        retention-days: 5