# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: TestBucket

on:
   workflow_dispatch:
     branches: [ "main" ]
    inputs:
      testSuite:
        description: 'The test suite to run'
        required: false
        default: 'TestBucket.Domain.UnitTests'
        type: choice
        options:
          - 'TestBucket.Domain.UnitTests'
          - 'TestBucket.Domain.IntegrationTests'
          - 'TestBucket.Domain.UnitTests'
          - 'TestBucket.Blazor.Tests'
          - 'TestBucket.Formats.UnitTests'
          - 'TestBucket.Traits.Core.UnitTests'
          - 'TestBucket.CodeCoverage.Tests'
jobs:
  build:

    runs-on: ubuntu-latest

    env:
      DOTNET_INSTALL_DIR: "./.dotnet"

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.102
    - name: Restore dependencies
      run: dotnet restore src/TestBucket.sln

    - name: Build
      run: dotnet build --no-restore src/TestBucket.sln
   
    - name: Unit Tests
      shell: pwsh
      run: ./run_tests.ps1 --testSuite {{ inputs.testSuite }}
   
    - name: Integration Tests
      shell: pwsh
      run: ./run_integration_tests.ps1 --testSuite {{ inputs.testSuite }}

    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      with:
        name: "Test Results"
        path: "**/TestResults/xunit.xml"
        retention-days: 2
        if-no-files-found: error